[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
logfile=%(here)s/supervisord/logs/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=%(here)s/supervisord/logs
nodaemon=false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[include]
files = %(here)s/supervisord/programs/*.ini
