[inet_http_server]
port=0.0.0.0:9001
username=supervisor
password=%(ENV_UPLOAD_TOKEN_SECRET)s

[supervisord]
logfile=%(here)s/supervisord/logs/supervisord.log
pidfile=%(here)s/supervisord/supervisord.pid
childlogdir=%(here)s/supervisord/logs
nodaemon=false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://runner:9001
username=supervisor
password=%(ENV_UPLOAD_TOKEN_SECRET)s

[include]
files = %(here)s/supervisord/programs/*.ini
