logLevel: info

authInternalUsers:
  - user: any
    permissions:
      - action: publish
      - action: read
      - action: playback
      - action: api
      - action: metrics

api: yes
apiAddress: :9997

metrics: yes
metricsAddress: :9998

rtmp: yes
rtmpAddress: :1935

pathDefaults:
  source: publisher

paths:
  all_others:
